name: Kiểm thử FastAPI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cài đặt dependencies
        run: |
          pip install fastapi uvicorn
          npm install

      - name: Khởi động FastAPI backend
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8080 &
          sleep 5

      - name: Chạy kiểm thử
        run: npm test