name: Deploy chatbot to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Chatbot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode service account key
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: chatbotai-467402
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with service account
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project chatbotai-467402

      - name: Enable required APIs
        run: |
          gcloud services enable run.googleapis.com
          gcloud services enable cloudbuild.googleapis.com

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/chatbotai-467402/chatbot .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chatbot \
            --image gcr.io/chatbotai-467402/chatbot \
            --region asia-southeast1 \
            --update-env-vars MONGO_URI="mongodb+srv://longtaiew01:Tancuong2028@chatbot.snfe5gt.mongodb.net/?retryWrites=true&w=majority&appName=chatbot",PDF_PATH=/app/trainchatbot.pdf,CHROMA_PATH=/app/data \
            --platform managed \
            --allow-unauthenticated \
            --timeout=600 \
            --memory=4Gi \
            

      - name: Wait for service to be ready
        run: |
          echo "⏳ Waiting for Cloud Run service to be ready..."
          for i in {1..10}; do
            STATUS=$(gcloud run services describe chatbot --region asia-southeast1 --format='value(status.conditions[0].status)')
            if [ "$STATUS" == "True" ]; then
              echo "✅ Service is ready!"
              break
            fi
            echo "Still starting... retry in 10s"
            sleep 10
          done

      - name: Allow unauthenticated invocations
        run: |
          gcloud run services add-iam-policy-binding chatbot \
            --region asia-southeast1 \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --project chatbotai-467402
