name: Deploy chatbot to Cloud Run
#ver1
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Chatbot
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Decode service account key
      run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json
      
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: chatbotai-467402
        service_account_key: ${{ secrets.CHATBOT_SA_KEY }}
        export_default_credentials: true
    - name: Authenticate with service account
      run: |
        gcloud auth activate-service-account 622933104662-compute@developer.gserviceaccount.com --key-file=key.json
        gcloud config set account 622933104662-compute@developer.gserviceaccount.com
        gcloud config set project chatbotai-467402

    - name: Enable required APIs
      run: |
        gcloud services enable run.googleapis.com
        gcloud services enable cloudbuild.googleapis.com

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/chatbotai-467402/chatbot .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy chatbot \
          --image gcr.io/chatbotai-467402/chatbot \
          --region asia-southeast1 \
          --platform managed \
          --member=allUsers \
          --role=roles/run.invoker \
          --allow-unauthenticated \
          --timeout=600s \
          --memory=1Gi
